const assert = require("node:assert/strict");
const fs = require("node:fs");

const source = fs.readFileSync("FL_Tools_Basic.user.js", "utf8");
const headerVersion = source.match(/^\/\/ @version\s+(\S+)/m)?.[1];
const runtimeVersion = source.match(/const FL_TOOLS_VERSION = "([^"]+)";/)?.[1];

assert.ok(headerVersion, "userscript version is present");
assert.equal(runtimeVersion, headerVersion, "runtime and metadata versions match");
assert.match(source, /const FL_SETTINGS_SCHEMA = 1;/, "settings schema is explicit");
assert.match(source, /migrateFlSettings\(\);/, "legacy settings migrate at startup");
assert.match(source, /About & diagnostics/, "diagnostics panel is available");
assert.match(source, /Copy diagnostics/, "diagnostics can be copied");
assert.doesNotMatch(source, /type=["']checkbox["']/i, "settings do not use checkbox inputs");
assert.match(source, /<button id=\"' \+ id \+ '\" type=\"button\" class=\"fl-switch-input toggleSwitch\" role=\"switch\"/, "switches are real buttons");
assert.match(source, /aria-checked/, "switches expose accessible state");
assert.match(source, /prefers-reduced-motion:reduce/, "reduced-motion preference is respected");
assert.match(source, /fl-tools-high-contrast/, "high-contrast mode is available");
assert.match(source, /userscript-launcher-v1/, "launcher coordination protocol is declared");
assert.match(source, /owner:"TypicalBits", id:"fl-tools-basic", priority:50, preferredPosition:"right-bottom"/, "launcher identity and placement priority are explicit");
assert.match(source, /launcherOccupiedArea/, "occupied launcher area is published");
assert.match(source, /userscript-launcher:change/, "launcher changes are announced");
assert.match(source, /const VISUAL_CARD_SELECTOR = "\.w-full\.rounded-sm\.cursor-pointer"/, "member-card visual selector is defined");
assert.match(source, /FL_SHORTCUT_DEFAULTS = \{ filters:"F", nsfw:"S", next:"N", top:"T" \}/, "keyboard defaults remain compatible");
assert.match(source, /data-fl-shortcut/, "shortcuts can be edited or disabled");
assert.match(source, /Shortcut collision detected/, "shortcut collisions are reported");
assert.match(source, /launcherShortcutCollision/, "live companion collisions are published");
assert.match(source, /BEGIN generated:handoff/, "handoff is synced from core/handoff.js");
assert.match(source, /BEGIN generated:css-core/, "dock CSS is synced from assets/fl-tools-core.css");
assert.match(source, /FLToolsCore/, "shared handoff API is published");
assert.match(source, /fl-tools-capabilities-v1/, "edition publishes the capability protocol");
assert.match(source, /edition: FL_EDITION/, "capability announcement identifies its edition");
assert.match(source, /fl-tools-studio-primary #fl-settings-launcher/, "launcher yields to live Studio");
assert.doesNotMatch(source, /"pro\.[a-z-]+"/, "Basic does not announce Pro capabilities");
assert.match(source, /fl-tools-core-style/, "shared core stylesheet id is used");
assert.doesNotMatch(source, /^\/\/ @require\b.*releases\/latest\//m, "Basic does not @require /releases/latest/");
assert.match(fs.readFileSync("assets/fl-tools-core.css", "utf8"), /--lt-accent:\s*#e11d48/, "core CSS tokens live in the asset");
assert.match(fs.readFileSync("assets/fl-tools-pro.css", "utf8"), /html\.fl-tools-dock-hidden/, "Pro-only chrome is separable");
assert.match(fs.readFileSync("core/handoff.js", "utf8"), /var FRESH_MS = 4000/, "handoff freshness window is explicit");
console.log("UI contract OK");
