const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const source = fs.readFileSync(path.join(root, "FL_Tools_Basic.user.js"), "utf8");
const headerVersion = source.match(/^\/\/ @version\s+(\S+)/m)?.[1];
const runtimeVersion = source.match(/const FL_TOOLS_VERSION = "([^"]+)";/)?.[1];

assert.ok(headerVersion, "userscript version is present");
assert.equal(runtimeVersion, headerVersion, "runtime and metadata versions match");
assert.match(source, /const FL_SETTINGS_SCHEMA = 1;/, "settings schema is explicit");
assert.match(source, /migrateFlSettings\(\);/, "legacy settings migrate at startup");
assert.match(source, /About & diagnostics/, "diagnostics copy lives in Performance");
assert.match(source, /Copy diagnostics/, "diagnostics can be copied");
assert.doesNotMatch(source, /id="fl-diagnostics-panel"/, "About is nested in Performance, not a separate dock panel");
assert.doesNotMatch(source, /cardIdentityLabels/, "identity is not painted as chips on list cards");
assert.doesNotMatch(source, /lt-id-chip/, "identity chip class is gone");
assert.doesNotMatch(source, /type=["']checkbox["']/i, "settings do not use checkbox inputs");
assert.match(source, /<button id=\"' \+ id \+ '\" type=\"button\" class=\"fl-switch-input toggleSwitch\" role=\"switch\"/, "switches are real buttons");
assert.match(source, /aria-checked/, "switches expose accessible state");
assert.match(source, /prefers-reduced-motion:reduce/, "reduced-motion preference is respected");
assert.match(source, /fl-tools-high-contrast/, "high-contrast mode is available");
assert.match(source, /userscript-launcher-v1/, "launcher coordination protocol is declared");
assert.match(source, /owner:"TypicalBits", id:"fl-tools-basic", priority:50, preferredPosition:"right-bottom"/, "launcher identity and placement priority are explicit");
assert.match(source, /launcherOccupiedArea/, "occupied launcher area is published");
assert.match(source, /userscript-launcher:change/, "launcher changes are announced");
assert.match(source, /const VISUAL_CARD_SELECTOR = "\.w-full\.rounded-sm\.cursor-pointer"/, "member-card visual selector is defined");
assert.match(source, /lt-card-chips/, "list cards get a visible chip rail");
assert.match(source, /id = "fl-browse-chips"/, "kinksters pages show active filter chips without opening the dock");
assert.match(source, /FL_SHORTCUT_DEFAULTS = \{ filters:"F", nsfw:"S", next:"N", top:"T" \}/, "keyboard defaults remain compatible");
assert.doesNotMatch(source, /data-fl-shortcut/, "shortcut rebinding belongs to Pro");
assert.match(source, /launcherShortcutCollision/, "live companion collisions are published");
assert.doesNotMatch(source, /id="fl-org-mode"/, "org cards belong to Pro");
assert.doesNotMatch(source, /function buildDisplayPanel/, "empty Display panel stub is gone");
assert.doesNotMatch(source, /function unnestFromToolsStack/, "v5 Tools nest migrator is gone");
assert.doesNotMatch(source, /fl-quick-save/, "Quick Save scavenger is gone");
assert.doesNotMatch(source, /fl-load-more/, "Load Next button chrome is gone");
assert.match(source, /BEGIN generated:handoff/, "handoff is synced from core/handoff.js");
assert.match(source, /BEGIN generated:css-core/, "dock CSS is synced from assets/fl-tools-core.css");
assert.match(source, /BEGIN generated:scanner/, "candidate scanner is synced from fl-core");
assert.match(source, /BEGIN generated:page-tweaks/, "silent page helpers are synced from fl-core");
assert.match(source, /BEGIN generated:storage/, "namespaced storage is synced from fl-core");
assert.match(source, /FLStorage\.set/, "Basic writes through FLStorage");
assert.match(source, /function bindPageTweaks/, "page helpers bind once at boot");
assert.match(source, /FLPageTweaks\.tick/, "page helpers run through tick()");
assert.match(source, /pageTweaksYield/, "Basic yields page helpers to live Pro");
assert.match(source, /function bindCandidateScanner/, "editions register kind handlers");
assert.match(source, /new MutationObserver\(ingestAddedNodes\)/, "mutations go through the candidate scanner");
assert.doesNotMatch(source, /if \(!member && !story\) continue;\s*schedule\(\)/, "mutations no longer rerun every module");
assert.match(source, /FLToolsCore/, "shared handoff API is published");
assert.match(source, /fl-tools-capabilities-v1/, "edition publishes the capability protocol");
assert.match(source, /edition: FL_EDITION/, "capability announcement identifies its edition");
assert.match(source, /fl-tools-studio-primary/, "Studio live class is still stamped");
assert.doesNotMatch(source, /fl-tools-studio-primary #fl-settings-launcher\{display:none/, "Studio does not hide the Basic launcher");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-block-panel \{ order: 1; \}/, "Soft-block is first in the dock");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-filter-panel \{ order: 2; \}/, "Filters follow Soft-block");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-system-panel \{ order: 5; \}/, "System is the last accordion");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-advanced-panel \{ order: 1; \}/, "System lists Advanced first");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-perf-controls \{ order: 2; \}/, "System lists Performance after Advanced");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-shortcuts-panel \{ order: 3; \}/, "System lists Shortcuts last");
assert.match(source, /mountDockSection\(document.getElementById\("fl-advanced-panel"\), "fl-advanced-panel"\);[\s\S]*mountDockSection\(document.getElementById\("fl-perf-controls"\), "fl-perf-controls"\);[\s\S]*mountDockSection\(document.getElementById\("fl-shortcuts-panel"\), "fl-shortcuts-panel"\)/, "System mounts Advanced, then Performance, then Shortcuts");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-dock-actions \{ order: 9; \}/, "Jump to top stays last");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /\.fl-tool-panel:has\(> \.fl-tool-header:hover\)/, "accordion rows glow on header hover");
assert.match(source, /function nestDockSections/, "NSFW and System children are nested, not extra dock rows");
assert.match(source, /systemPanel: "System"/, "System is a dock section");
assert.match(source, /FL_ACTION_PARENTS/, "Studio still opens nested panel ids via their parent");
assert.match(source, /fltools:action/, "Basic listens for Studio orchestration actions");
assert.match(source, /function openCapabilityPanel/, "Studio can open Basic dock panels");
assert.match(source, /"navigation\.next"/, "Basic announces navigation instead of rebinding");
assert.match(source, /"filter\.preset"/, "Basic announces filter presets");
assert.match(source, /label":"Open Filters"/, "Studio/palette copy capitalizes Filters");
assert.match(source, /Filters Menu/, "shortcut legend names the Filters Menu");
assert.match(source, /browseChips: "Active Filters"/, "browse chips label capitalizes Filters");
assert.match(fs.readFileSync(path.join(root, "README.md"), "utf8"), /\*\*Page helpers\*\* —/, "Basic README names the silent page helpers");
assert.match(source, /"seen\.reset"/, "Basic announces seen reset");
assert.match(source, /BEGIN generated:presets/, "browse presets are generated from fl-core");
assert.doesNotMatch(source, /id="fl-preset-row"/, "browse Default/Minimal/SFW presets are not duplicated on Filters");
assert.match(source, /data-fl-display-preset="minimal"/, "NSFW panel has Default/Minimal/SFW display presets");
assert.match(source, /function collapseInnerMenus/, "switching dock modules closes nested menus");
assert.match(source, /if \(exceptId && !keepParent\) collapseInnerMenus/, "reopening a dock row starts nested menus collapsed");
assert.doesNotMatch(source, /id="fl-loc-wrap"/, "Location filtering is FetLife's, not a dock subsection");
assert.doesNotMatch(source, /id="fl-same-city-only"/, "Same-city filter chrome is gone");
assert.doesNotMatch(source, /id="fl-cities"/, "city chips are not a dock control");
assert.match(source, /blockPanel: "Soft-Block \| Block"/, "Soft-Block | Block is the panel title");
assert.match(source, /factoryReset: "Factory Reset"/, "Advanced includes Factory Reset");
assert.match(source, /function wipeFlToolsStorage/, "Factory Reset wipes fl_ storage");
assert.match(source, /id="fl-factory-reset"/, "Factory Reset lives in Advanced");
assert.doesNotMatch(source, /document\.body\.appendChild\(overlay\)/, "confirms are not page overlays");
assert.match(source, /blockFetlifeContinue/, "FetLife block has a Continue confirm step");
assert.match(source, /id="fl-reset-seen"/, "Reset Seen is shipped");
assert.match(source, /flCanonicalCapability/, "Studio actions resolve aliases");
assert.match(source, /FL_EVENT_PAYLOAD_KEYS/, "event payloads are allowlisted");
assert.match(source, /function flEventPayload/, "generated helper sanitizes event payloads");
assert.match(source, /sessionStorage\.getItem\("fl_private_session"\) === "1"/, "generated publisher respects private session");
assert.doesNotMatch(
  source.slice(source.indexOf("BEGIN generated:catalog"), source.indexOf("END generated:catalog")),
  /organisation-cards|display\.org-cards|profile\.note/,
  "org cards and Pro people tools are not announced by Basic"
);
assert.match(source, /fl-tools-core-style/, "shared core stylesheet id is used");
assert.doesNotMatch(source, /^\/\/ @require\b.*releases\/latest\//m, "Basic does not @require /releases/latest/");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /a\.fl-visited-nick/, "visited nicknames have a dedicated tint");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /a\.fl-shared-kink/, "shared kinks are heavier and pink");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-core.css"), "utf8"), /#fl-list-pager-clone/, "list pager copy is styled");
assert.match(fs.readFileSync(path.join(root, "assets/fl-tools-pro.css"), "utf8"), /html\.fl-tools-dock-hidden/, "Pro-only chrome is separable");
assert.match(fs.readFileSync(path.join(root, "core/handoff.js"), "utf8"), /var FRESH_MS = 4000/, "handoff freshness window is explicit");
console.log("UI contract OK");
