#!/usr/bin/env node
/**
 * Single-source sync for FL Tools Basic.
 *
 * Sources of truth:
 *   assets/fl-tools-core.css  — tokens + dock/launcher chrome + Basic surface
 *   assets/fl-tools-pro.css   — Pro-only chrome (highlighter, hide, snooze, …)
 *   core/handoff.js           — live-yield / heartbeat API
 *
 * Generated (do not edit by hand):
 *   core/css-core.js
 *   core/css-pro.js
 *   marked regions inside FL_Tools_Basic.user.js
 *
 * Usage:
 *   node scripts/sync-core.mjs          # write generated files
 *   node scripts/sync-core.mjs --check  # exit 1 if generated output drifted
 *
 * Basic stays a standalone userscript (no @require). Pro may vendor these
 * files or @require a *tagged* Basic release asset — never /releases/latest/.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const MARK = {
  handoff: {
    begin: "  /* BEGIN generated:handoff */",
    end: "  /* END generated:handoff */"
  },
  cssCore: {
    begin: "  /* BEGIN generated:css-core */",
    end: "  /* END generated:css-core */"
  }
};

function read(rel) {
  return readFileSync(join(ROOT, rel), "utf8").replace(/\r\n/g, "\n");
}

function wrapCssInjector({ sourceRel, styleId, banner }) {
  const css = read(sourceRel).replace(/^\uFEFF/, "");
  const header = [
    `/* Generated by scripts/sync-core.mjs — do not edit.`,
    `   Source: ${sourceRel}`,
    `   ${banner} */`
  ].join("\n");
  return `${header}
(function () {
  if (document.getElementById(${JSON.stringify(styleId)})) return;
  var el = document.createElement("style");
  el.id = ${JSON.stringify(styleId)};
  el.textContent = ${JSON.stringify(css)};
  (document.documentElement || document.head).appendChild(el);
})();
`;
}

function indentBlock(text, spaces) {
  const pad = " ".repeat(spaces);
  return text.replace(/\s+$/, "").split("\n").map((line) => (line.length ? pad + line : line)).join("\n");
}

function replaceMarked(src, { begin, end }, body, label) {
  const start = src.indexOf(begin);
  const stop = src.indexOf(end);
  if (start < 0 || stop < 0 || stop < start) {
    throw new Error(`Missing ${label} markers (${begin.trim()} … ${end.trim()}) in FL_Tools_Basic.user.js`);
  }
  return src.slice(0, start) + begin + "\n" + body + "\n" + src.slice(stop);
}

function writeOrCheck(rel, next) {
  const abs = join(ROOT, rel);
  let prev = null;
  try { prev = readFileSync(abs, "utf8"); } catch (_) {}
  const normaliseEol = value => value == null ? value : value.replace(/\r\n/g, "\n");
  if (normaliseEol(prev) === normaliseEol(next)) return false;
  if (CHECK) {
    const why = prev == null ? "missing" : "out of date";
    throw new Error(`${rel} is ${why}. Run: node scripts/sync-core.mjs`);
  }
  writeFileSync(abs, next);
  return true;
}

const cssCoreJs = wrapCssInjector({
  sourceRel: "assets/fl-tools-core.css",
  styleId: "fl-tools-core-style",
  banner: "Injects shared dock tokens + chrome for Basic (and for Pro to vendor / @require)."
});
const cssProJs = wrapCssInjector({
  sourceRel: "assets/fl-tools-pro.css",
  styleId: "fl-tools-pro-style",
  banner: "Injects Pro-only chrome. Basic does not load this file."
});

let changed = [];
if (writeOrCheck("core/css-core.js", cssCoreJs)) changed.push("core/css-core.js");
if (writeOrCheck("core/css-pro.js", cssProJs)) changed.push("core/css-pro.js");

const handoffSrc = read("core/handoff.js").replace(/^\uFEFF/, "").replace(/\s+$/, "");
let userscript = read("FL_Tools_Basic.user.js");

const nextUserscript = replaceMarked(
  replaceMarked(
    userscript,
    MARK.handoff,
    indentBlock(handoffSrc, 2),
    "handoff"
  ),
  MARK.cssCore,
  indentBlock(cssCoreJs, 2),
  "css-core"
);

if (/\n\/\/ @require\b.*releases\/latest\//i.test(nextUserscript)) {
  throw new Error("Refusing to emit @require of /releases/latest/ — pin a tag or inline via this sync script.");
}

if (writeOrCheck("FL_Tools_Basic.user.js", nextUserscript)) changed.push("FL_Tools_Basic.user.js");

if (CHECK) {
  console.log("sync-core OK (generated files match assets/ + core/handoff.js)");
} else if (!changed.length) {
  console.log("sync-core: already up to date");
} else {
  console.log("sync-core wrote: " + changed.join(", "));
}
